---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: redpanda
  namespace: redpanda
spec:
  chart:
    spec:
      chart: redpanda
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: redpanda
  interval: 1m0s
  values:
    statefulset:
      replicas: 1
    console:
      enabled: false
  dependsOn:
    - name: cert-manager
      namespace: cert-manager
